# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#- task: cURLUploader@2
#  inputs:
#    files: 
    # Content: '*.jar'
    # authType: 'UserAndPass'
    # username: 'mounat'
    # password: '123456'
    # url: 'https://repo1.maven.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar'
    # remotePath: 'upload/$(Build.BuildId)/'



- task: cURLUploader@2
  inputs:
    files: 'commons-lang-2.6.jar'
    serviceEndpoint: 'Public Repo Maven'
    remotePath: 'upload/$(Build.BuildId)/'



# - task: CopyFiles@2
#   inputs:
#    SourceFolder: '$(Build.BuildId)'
#    Contents: '**/*.jar'
#    targetFolder: '$(Build.ArtifactStagingDirectory)'
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'dropJar'
#     publishLocation: 'Container'

