# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'mounat'
#     scannerMode: 'Other'
#     organization: 'mounat0'


- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'mounat'
    organization: 'mounat0'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Mounat0_DevopsTEST'
    cliProjectName: 'DevopsTEST'
    cliSources: '.'
- task: Maven@3
  inputs:
    mavenPomFile: 'devopstest/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: "1.6"
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenAuthenticateFeed: true
    sonarCloudRunAnalysis: true
    goals: 'package'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

# 9alk khas n copy so i can publish the build artifact
# not used anymore if m gonna use a pipeline artifact
- task: CopyFiles@2
  inputs:
   Contents: '**/*.war'
   targetFolder: '$(Build.ArtifactStagingDirectory)'
   
#this task is to publish 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
