# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: cURLUploader@2
  inputs:
    files: '**/*.jar'
    authType: 'UserAndPass'
    username: 'mounat'
    password: '123456'
    url: 'https://www-eu.apache.org/dist//commons/lang/source/commons-lang-2.6-src.zip'
    remotePath: 'upload/$(Build.ArtifactStagingDirectory)/'

- task: CopyFiles@1
  inputs:
   Contents: '**/*.jar'
   targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dropJar'
    publishLocation: 'Container'